# Generated by Django 5.1.7 on 2025-06-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image2',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='menu.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.CreateModel(
            name='GalleryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/menu_items')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
